[package]
name = "loco-protocol"
version = "0.0.1"
authors = ["storycraft <storycraft@pancake.sh>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"
openssl = "0.10.30"